### PR TITLE
fix: Add module.exports line (#154)

### PR DESCRIPTION
**Pull request by phrakture**
I am not entirely clear on why this has not bitten anyone else...

### CODE REVIEW

**Comment by phrakture** [comment]
It's an internal project, with a more complex babelrc setup. I can probably pare it down with some effort. However, it's worth noting that a vast majority of Babel plugins include this line.

**Comment by bcoe** [comment]
@phrakture is there a project on GitHub you can link me to to reference? It feels like a bug with `babel-plugin-istanbul`'s use of babel if this line is necessary, as I think this should be being handled by:

`export default makeVisitor`.

**Comment by phrakture** [comment]
Sadly, it's an internal project.

**Comment by coreyfarrell** [comment]
> However, it's worth noting that a vast majority of Babel plugins include this line.

@phrakture could you point us to one?  The standard babel plugins (at least babel 7) do not include this.

**Comment by phrakture** [comment]
Eeks, sorry didn't see this reply.

I think it was in Babel 6.x where I saw that, and I was just grepping
through a node_modules directory at the time.

**Comment by coreyfarrell** [comment]
@phrakture I'm not seeing it.  In addition the generated file `lib/index.js` starts with:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
```
I don't think you are experiencing a bug in babel-plugin-istanbul as the generated code exports stuff the same way as official babel plugins.  I understand your project is internal and you cannot share it but to help I need to see a 'bug demo'.  A 'hello world' scale project with just enough to show the problem you are experiencing.  In any case I believe the solution will be a slight change to your babelrc.

**Comment by phrakture** [comment]
Sorry, I've managed to solve this problem by upgrading a whole bunch of
things.

I am totally happy to just close this out.

**Comment by coreyfarrell** [comment]
Thanks for replying.

**Pull request closed without merging**
