### PR TITLE
Pass realpath(process.cwd()) to test-exclude

### PR DESCRIPTION
**Pull request by motiz88**
This is a fix for #7.

### CODE REVIEW

**Comment by bcoe** [comment]
@motiz88 looks like you might have bit by standard formatting nits.

**Comment by motiz88** [comment]
Oops! Right. I've now force-pushed an edited commit.

**Comment by bcoe** [comment]
@motiz88 looks good, I'll test this against some of my projects. This fixed the problem for you on your project?

**Comment by motiz88** [comment]
Yes. For the record, this was on my Windows dev machine, running tests from path like `C:\gh\project` where `C:\gh` is a symlink to `C:\Users\Moti Z\Documents\GitHub`.

**Comment by bcoe** [comment]
@motiz88 this is published in `babel-plugin-istanbul@1.0.2` take it for a spin.

**Pull request merged**
