### PR TITLE
Fix for #7: take realpath of cwd, whether or not set in env

### LINKED ISSUE #7: Files are erroneously ignored if process.cwd() contains symlinks
1) `babel-plugin-istanbul` preprocesses paths with `realpath()` before filtering them with `test-exclude`.
2) `test-exclude` excludes paths that are outside of `process.cwd()`.

When `process.cwd()` includes symlinks, the use of `realpath()` means that _all_ files will appear to be outside of the working directory.

Possible solutions:
##### A) Resolve `process.cwd()` with `realpath()` too
(PR #8 does this)
```javascript
    exclude = testExclude({
      cwd: getRealpath(process.cwd()),
//...
```

Or alternatively:
##### B) Don't use `realpath()` on any files at all
There may, of course, be a good reason to keep using `realpath()` that I'm not aware of.

### PR DESCRIPTION
**Pull request by motiz88**
Fixes #7

### CODE REVIEW

**Comment by bcoe** [comment]
@motiz88 👍 this was the fix I was thinking of implementing too, glad it works; I would love to figure out a failing test though, perhaps if we muck with process.cwd in the test?

**Comment by bcoe** [comment]
@motiz88 just following up, any thoughts about how we could get a test around this, so that we can avoid another regression?

**Comment by motiz88** [comment]
@bcoe I'm giving it a shot now using a mock for `fs` etc.

**Comment by motiz88** [comment]
Okay, that touched a lot more than I would have liked, but we have tests now!

Mocking `fs` and `process` went smoothly enough, but then I hit some issues that required more changes (e.g. [`shouldSkip` now passes the same `cwd` to `testExclude` and `findUp`](https://github.com/istanbuljs/babel-plugin-istanbul/pull/37/commits/c225334ca1f954746c94b13dc7a09fa3edb93f5c#diff-1fdf421c05c1140f6d71444ea2b27638R23)).

One remaining tangential issue is Node version support - I noticed you're still testing against 0.10. I could work around the lack of `Object.assign` in there or we can drop support for Node versions <= 4. @bcoe, what do you prefer?

**Comment by bcoe** [comment]
@motiz88 bump, would like to land this but let's pull in `lodash.assign` for the time being 👍

**Comment by bcoe** [comment]
@motiz88 could you please give this a spin:

`npm cache clear; npm i babel-plugin-istanbul@next`

It has your changes.

**Comment by motiz88** [comment]
:+1: Looks good!

**Comment by bcoe** [comment]
@motiz88 weird issue, at some point a dependency of a dependency seems to have introduced a regression that makes mock-fs hang tests permanently.

**Pull request merged**
