### PR TITLE
Update package dependencies and Babel configurations

### PR DESCRIPTION
**Pull request by zodman**
```

> babel-plugin-istanbul@6.1.1 pretest
> standard && npm run release


> babel-plugin-istanbul@6.1.1 release
> babel src --out-dir lib

Successfully compiled 2 files with Babel (167ms).

> babel-plugin-istanbul@6.1.1 test
> cross-env NODE_ENV=test nyc --reporter=lcov --reporter=text mocha --timeout 5000 test/*.js



  babel-plugin-istanbul
    Babel plugin config
      ✔ should instrument file if shouldSkip returns false (56ms)
      ✔ should not instrument file if shouldSkip returns true
      ✔ should call onCover callback
      local node_modules
        ✔ should instrument file if shouldSkip returns false
        ✔ should not instrument file if shouldSkip returns true
    source maps
      ✔ should use inline source map
      ✔ should not use inline source map if inputSourceMap is set to false
      ✔ should use provided source map
    instrument options
      ✔ should honor coverageVariable option
      ✔ should honor coverageGlobalScope option
      ✔ should honor coverageGlobalScope option
      ✔ should honor ignoreClassMethods option
    package.json "nyc" config
      process.env.NYC_CONFIG is set
        ✔ should instrument file if shouldSkip returns false
        ✔ should not instrument file if shouldSkip returns true
      process.env.NYC_CONFIG is not set
        ✔ should instrument file if shouldSkip returns false (349ms)
        ✔ should not instrument file if shouldSkip returns true
        ✔ should load config using cwd (1094ms)
    regression tests
      ✔ should instrument: export const foo = () => {}
      ✔ should not conflict with transform-modules-commonjs (45ms)


  19 passing (2s)

-------------------------|---------|----------|---------|---------|-------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------|---------|----------|---------|---------|-------------------
All files                |     100 |      100 |     100 |     100 |                   
 index.js                |     100 |      100 |     100 |     100 |                   
 load-nyc-config-sync.js |     100 |      100 |     100 |     100 |                   
-------------------------|---------|----------|---------|---------|-------------------

```

### CODE REVIEW

**Comment by SimenB** [comment]
CI is very unhappy here 😅 

Some of the updates landed in #292, but happy to update more deps if you can make CI pass 🙂

**Comment by anomiex** [comment]
I suspect you'll need to merge the changes from master, then bump the node version to 18 in
https://github.com/istanbuljs/babel-plugin-istanbul/blob/37bb294cf433ca327572a2c3e1e4e6c32484c16e/package.json#L70
drop the tests against node <18 at
https://github.com/istanbuljs/babel-plugin-istanbul/blob/37bb294cf433ca327572a2c3e1e4e6c32484c16e/.github/workflows/ci.yaml#L13
and bump the node-version in a few other places too
https://github.com/istanbuljs/babel-plugin-istanbul/blob/37bb294cf433ca327572a2c3e1e4e6c32484c16e/.github/workflows/ci.yaml#L28
https://github.com/istanbuljs/babel-plugin-istanbul/blob/37bb294cf433ca327572a2c3e1e4e6c32484c16e/.github/workflows/release-please.yml#L19

**Comment by zodman** [comment]
working on it ...

**Comment by SimenB** [comment]
FYI, I won't merge if it drops Node 16 as I need that version to be supported in Jest

**Comment by anomiex** [comment]
That's very unfortunate, since that will prevent fixing #294, which means Jest will be continuing to raise the scary deprecation warnings for everyone.

I see `test-exclude` is also under istanbuljs. Would you, @SimenB, be willing to fix that package to restore Node 16 compat since that's a requirement for you? At a quick glance, despite istanbuljs/test-exclude#56 saying that updating deps was the reason for making Node 18 the minimum, I don't see any deps that don't say they support Node 16.

**Comment by zodman** [comment]
I saw the update to version 7 what it was something I lookup thanks!

**Pull request closed without merging**
